from __future__ import annotations

import re
import unittest
from pathlib import Path

import validate_suite


ROOT = Path(__file__).resolve().parents[1]
EXPECTED_SKILLS = ("quant-plan", "quant-goal", "quant-developer")


def read(relative: str) -> str:
    return (ROOT / relative).read_text(encoding="utf-8")


def skill_text(name: str) -> str:
    return read(f"skills/{name}/SKILL.md")


def agent_text(name: str) -> str:
    return read(f"skills/{name}/agents/openai.yaml")


def normalized(text: str) -> str:
    return " ".join(text.lower().split())


def table_rows(text: str) -> tuple[str, ...]:
    return tuple(
        line.strip()
        for line in text.splitlines()
        if line.strip().startswith("|") and "---" not in line
    )


class SkillRoutingTests(unittest.TestCase):
    def test_exactly_three_explicit_only_public_skills(self) -> None:
        discovered = {
            path.parent.name
            for path in (ROOT / "skills").glob("*/SKILL.md")
        }
        self.assertEqual(discovered, set(EXPECTED_SKILLS))
        for name in EXPECTED_SKILLS:
            metadata = validate_suite.frontmatter(skill_text(name))
            agent = validate_suite.agent_metadata(agent_text(name))
            with self.subTest(skill=name):
                self.assertEqual(metadata.get("name"), name)
                self.assertIn(f"${name}", metadata.get("description", ""))
                self.assertIsNotNone(agent)
                assert agent is not None
                self.assertIs(agent["allow_implicit_invocation"], False)
                self.assertIn(f"${name}", str(agent["default_prompt"]))

    def test_selector_metadata_requires_all_trust_dimensions(self) -> None:
        mutations = (
            ("trusted current-user", "untrusted current-user"),
            ("current-user, same-request", "current-user, unrelated-request"),
            (
                "metadata generated by that\nselector",
                "metadata generated by another\nselector",
            ),
        )
        for name in EXPECTED_SKILLS:
            original = skill_text(name)
            self.assertTrue(validate_suite.has_selector_metadata_clause(original, name))
            for old, new in mutations:
                with self.subTest(skill=name, mutation=old):
                    mutated = original.replace(old, new, 1)
                    self.assertNotEqual(mutated, original)
                    self.assertFalse(
                        validate_suite.has_selector_metadata_clause(mutated, name)
                    )

    def test_continuation_is_same_unfinished_task_only(self) -> None:
        for name in EXPECTED_SKILLS:
            original = skill_text(name)
            with self.subTest(skill=name):
                self.assertTrue(
                    validate_suite.has_trusted_same_task_continuation(original)
                )
                self.assertTrue(
                    validate_suite.has_bounded_continuation_exclusion(original)
                )
                body = normalized(original)
                self.assertRegex(
                    body,
                    r"without (?:it|either).{0,60}require a fresh selector",
                )
                self.assertIn("completed or unrelated task", body)
                self.assertIn("worker instruction", body)

            unsafe = original.replace(
                "same unfinished,\nalready-active task",
                "any prior task",
                1,
            )
            self.assertFalse(validate_suite.has_trusted_same_task_continuation(unsafe))

    def test_activation_exclusions_share_the_non_activation_clause(self) -> None:
        for name in EXPECTED_SKILLS:
            body = normalized(skill_text(name))
            clause = next(
                part
                for part in re.split(r"(?<=[.!?])\s+", body)
                if "semantic match" in part
            )
            with self.subTest(skill=name):
                for term in (
                    "quoted",
                    "negated",
                    "prior-turn selection",
                    "completed",
                    "unrelated",
                    "worker instruction",
                    "does not activate or continue",
                ):
                    self.assertIn(term, clause)

    def test_kernel_skip_is_fail_closed_on_unknown_scope(self) -> None:
        safe_paraphrases = (
            "If uncertain, read the kernel routing table before deciding to skip it.",
            "When unsure, consult the kernel router before skipping it.",
            "When unsure, do not skip without consulting the kernel router.",
            "If uncertain about whether to skip, read the kernel routing table first.",
            "If uncertain, never skip before consulting the kernel router.",
            "If uncertain, skipping without reading the kernel router is prohibited.",
        )
        unsafe = (
            "If uncertain, skip without checking the kernel router.",
            "If uncertain, avoid reading the kernel before skipping it.",
            "If uncertain, skip before reading the kernel routing table.",
            "If uncertain, the kernel routing table may be skipped.",
            "You may skip the kernel routing table if uncertain.",
            "Skip the kernel router whenever unsure.",
            "The kernel router may be skipped when uncertain.",
            "Kernel consultation is optional when unsure whether to skip.",
            "If uncertain, read the kernel routing table after skipping it.",
            "If uncertain, before consulting the kernel router, skip it.",
            "If uncertain, without consulting the kernel router, skip it.",
            "If uncertain, the kernel need not be read before skipping it.",
        )
        for phrase in safe_paraphrases:
            self.assertTrue(validate_suite.has_guarded_kernel_skip(phrase))
        for phrase in unsafe:
            self.assertFalse(validate_suite.has_guarded_kernel_skip(phrase))
            self.assertTrue(validate_suite.has_unsafe_kernel_skip(phrase))

        for name in EXPECTED_SKILLS:
            with self.subTest(skill=name):
                original = skill_text(name)
                self.assertTrue(validate_suite.has_guarded_kernel_skip(original))
                self.assertFalse(validate_suite.has_unsafe_kernel_skip(original))
                appended = (
                    f"{original}\n\nIf uncertain, skip before reading the kernel "
                    "routing table."
                )
                self.assertTrue(validate_suite.has_unsafe_kernel_skip(appended))
                self.assertTrue(validate_suite._validate_public_skill(name, appended))

        plan = skill_text("quant-plan")
        canonical = (
            "If uncertain, read the kernel routing table before deciding to skip it."
        )
        for inversion in (
            "If uncertain, skip before reading the kernel routing table.",
            "If uncertain, the kernel routing table may be skipped.",
        ):
            with self.subTest(full_document_inversion=inversion):
                mutated = plan.replace(canonical, inversion, 1)
                self.assertTrue(validate_suite.has_unsafe_kernel_skip(mutated))
                self.assertTrue(
                    validate_suite._validate_public_skill("quant-plan", mutated)
                )

    def test_public_shared_routes_are_closed_and_symmetric(self) -> None:
        available = validate_suite.BASE_SHARED_FILES
        shared = ROOT / "shared"
        for name in EXPECTED_SKILLS:
            text = skill_text(name)
            source, installed = validate_suite.extract_public_shared_routes(text)
            with self.subTest(skill=name):
                self.assertEqual(source, installed)
                self.assertEqual(
                    validate_suite.validate_public_routes(
                        name,
                        text,
                        shared,
                        available,
                    ),
                    [],
                )

    def test_role_composition_preserves_stage_owners(self) -> None:
        plan = normalized(skill_text("quant-plan"))
        goal = normalized(skill_text("quant-goal"))
        developer = normalized(skill_text("quant-developer"))
        router = normalized(read("shared/core/context-routing.md"))
        self.assertIn("planning does not authorize implementation", plan)
        self.assertIn("goal owner", goal)
        self.assertIn("developer then owns selected implementation", goal)
        self.assertIn("this role never changes the parent goal", developer)
        self.assertIn("composition never expands authority", router)

    def test_goal_binding_precedes_plan_and_developer(self) -> None:
        goal = normalized(skill_text("quant-goal"))
        binding = goal.index("call `get_goal` before plan, developer")
        composition = goal.index("after binding, quant plan")
        terminal = goal.index('update_goal(status="complete")')
        self.assertLess(binding, composition)
        self.assertLess(composition, terminal)
        self.assertIn("workers never call lifecycle tools", goal)

    def test_base_routes_are_observable_all_conditions_gates(self) -> None:
        plan = normalized(skill_text("quant-plan"))
        developer = normalized(skill_text("quant-developer"))
        goal = normalized(skill_text("quant-goal"))
        self.assertIn("every condition is confirmed", plan)
        self.assertIn("if any condition is false or unknown", plan)
        self.assertIn("if any condition is false or unknown", developer)
        self.assertIn("only for a familiar single local component", goal)
        self.assertIn("otherwise read matching shared-kernel routes", goal)

    def test_capability_table_maps_only_observed_triggers(self) -> None:
        kernel = read("shared/references/adaptive-workflow.md")
        rows = "\n".join(table_rows(kernel))
        expected = {
            "calculation": "capabilities/analysis.md",
            "provider": "capabilities/external-data.md",
            "ui control": "capabilities/analysis-input-flow.md",
            "layout": "capabilities/web-ui.md",
            "api boundary": "capabilities/backend.md",
            "dirty or overlapping": "capabilities/repo-mutation.md",
            "recurring": "capabilities/scheduled-automation.md",
            "versioned artifact": "capabilities/publication.md",
            "public url": "capabilities/public-web.md",
            "authorized push": "capabilities/remote-release.md",
            "real interruption": "capabilities/long-running-recovery.md",
        }
        for trigger, route in expected.items():
            with self.subTest(trigger=trigger):
                row = next(line for line in rows.splitlines() if trigger in line.lower())
                self.assertIn(route, row)
        self.assertIn("select a row from observed scope", normalized(kernel))

    def test_one_off_wait_is_not_persistent_automation(self) -> None:
        raw_kernel = read("shared/references/adaptive-workflow.md")
        wait_row = next(
            normalized(row)
            for row in table_rows(raw_kernel)
            if "one-off wait" in row.lower()
        )
        self.assertIn("host lifecycle", wait_row)
        self.assertIn("do not select scheduled automation", wait_row)
        self.assertIn("persistent recurring or provider-triggered", wait_row)
        self.assertIn("never busy poll", normalized(raw_kernel))

    def test_recovery_is_optional_and_never_grants_authority(self) -> None:
        recovery = read("shared/capabilities/long-running-recovery.md")
        errors = validate_suite.validate_recovery_body(recovery)
        self.assertEqual(errors, [])
        body = normalized(recovery)
        self.assertIn("real interruption", body)
        self.assertIn("`$quant-plan` remains read-only", body)
        self.assertIn("native goal or task", body)
        self.assertIn("remain canonical", body)

    def test_policy_red_team_rejects_expansion(self) -> None:
        plan = skill_text("quant-plan")
        developer = skill_text("quant-developer")
        goal = skill_text("quant-goal")
        self.assertIn(
            "quant-plan: probe must not permit provider writes or unsafe "
            "dependency installation",
            validate_suite._validate_public_skill(
                "quant-plan",
                plan + "\nProvider writes are permitted during a probe.\n",
            ),
        )
        self.assertIn(
            "quant-developer: open-ended improvement loop is prohibited",
            validate_suite._validate_public_skill(
                "quant-developer",
                developer + "\nContinue after acceptance while polish remains.\n",
            ),
        )
        self.assertIn(
            "quant-goal: universal completion-condition IDs are prohibited",
            validate_suite._validate_public_skill(
                "quant-goal",
                goal + "\nEvery completion condition needs a stable ID.\n",
            ),
        )

    def test_legacy_runtime_is_explicit_compatibility_only(self) -> None:
        router = normalized(read("shared/core/context-routing.md"))
        self.assertIn("legacy compatibility path", router)
        self.assertIn("existing project depends on the exact contract", router)
        self.assertIn("explicitly requests machine-audited output", router)
        for name in EXPECTED_SKILLS:
            body = normalized(skill_text(name))
            with self.subTest(skill=name):
                self.assertIn("existing exact contract", body)
                self.assertIn("explicit machine audit", body)


if __name__ == "__main__":
    unittest.main()
