from __future__ import annotations

import json
import shutil
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
import validate_suite as suite_validator
import install as suite_installer


class PackageShapeValidationTests(unittest.TestCase):
    def copy_suite(self, directory: str) -> Path:
        target = Path(directory) / "quant-research-suite"
        shutil.copytree(
            ROOT,
            target,
            ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
        )
        return target

    def validate_copy(self, root: Path) -> list[str]:
        with mock.patch.object(suite_validator, "ROOT", root):
            return suite_validator.validate()

    def test_permits_only_intended_files_and_ignored_bytecode(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = self.copy_suite(directory)
            cache = root / "tests" / "__pycache__"
            cache.mkdir()
            (cache / "test_package_shape.cpython-313.pyc").write_bytes(
                b"generated bytecode fixture"
            )

            self.assertEqual(self.validate_copy(root), [])

    def test_installed_shared_root_contains_documented_goal_resources(
        self,
    ) -> None:
        shared = suite_installer.INSTALL_ITEMS["quant-research-shared"]
        self.assertEqual(shared.resolve(), (ROOT / "shared").resolve())
        for relative in (
            "core/context-routing.md",
            "references/goal-and-subagents.md",
            "references/durable-runtime.md",
            "scripts/goal_ledger.py",
        ):
            with self.subTest(relative=relative):
                self.assertTrue((shared / relative).is_file())

    def test_rejects_unexpected_and_environment_files(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = self.copy_suite(directory)
            (root / "notes.txt").write_text("unexpected\n", encoding="utf-8")
            (root / ".env").write_text("TOKEN=fixture\n", encoding="utf-8")

            errors = self.validate_copy(root)

            self.assertIn("unexpected package file: notes.txt", errors)
            self.assertIn(
                "secret-bearing artifact is prohibited: .env",
                errors,
            )
            self.assertIn("unexpected package file: .env", errors)

    def test_rejects_symlinks_and_secret_artifacts(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = self.copy_suite(directory)
            (root / "README-link.md").symlink_to(root / "README.md")
            (root / "private.pem").write_text(
                "-----BEGIN " + "PRIVATE KEY-----\nfixture\n",
                encoding="utf-8",
            )

            errors = self.validate_copy(root)

            self.assertIn("symlink is prohibited: README-link.md", errors)
            self.assertIn(
                "secret-bearing artifact is prohibited: private.pem",
                errors,
            )

    def test_rejects_obvious_secret_content_in_intended_file(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = self.copy_suite(directory)
            readme = root / "README.md"
            readme.write_text(
                readme.read_text(encoding="utf-8")
                + "\n-----BEGIN "
                + "PRIVATE KEY-----\nfixture\n",
                encoding="utf-8",
            )

            errors = self.validate_copy(root)

            self.assertIn(
                "obvious private key block content is prohibited: README.md",
                errors,
            )

    def test_rejects_unsealed_team_protocol_example(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = self.copy_suite(directory)
            packet = (
                root
                / "shared"
                / "templates"
                / "team-run-packet.example.json"
            )
            value = json.loads(packet.read_text(encoding="utf-8"))
            value["activation_reason"] = "Mutated after the packet was sealed."
            packet.write_text(
                json.dumps(value, indent=2) + "\n",
                encoding="utf-8",
            )

            errors = self.validate_copy(root)

            self.assertIn("team packet example self-hash is invalid", errors)


if __name__ == "__main__":
    unittest.main()
